tunnel: 2a731d6f-bfbc-4c32-a62f-b620049afae5
credentials-file: /home/teuzin/.cloudflared/2a731d6f-bfbc-4c32-a62f-b620049afae5.json

ingress:
  - hostname: gtm.yannrodrigues.com
    service: http://localhost:8080
    originRequest:
      connectTimeout: 30s
      tlsTimeout: 10s
      tcpKeepAlive: 30s
      keepAliveConnections: 10
      httpHostHeader: gtm.yannrodrigues.com
  - service: http_status:404 